### ISSUE TITLE
No such file or directory after entering capcha in firefox

### ISSUE THREAD

**Issue by vext01** [dnlcrl/PyScholar#3]
```
$ python2.7 pyscholar.py -c 1 --author "albert einstein" --phrase "quantum theory" 

/usr/local/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))
Traceback (most recent call last):
  File "pyscholar.py", line 225, in <module>
    sys.exit(main())
  File "pyscholar.py", line 221, in main
    querier.quit()
  File "/home/edd/PyScholar/src/query.py", line 468, in quit
    copytree(self.firefox.profile.path, FF_PROFILE_PATH)
  File "/usr/local/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('/tmp/tmpyJSdF2/webdriver-py-profilecopy/lock', '../ffprofile/lock', "[Errno 2] No such file or directory: '/tmp/tmpyJSdF2/webdriver-py-profilecopy/lock'")]
```

**Comment by vext01** [comment]
FWIW, it's just that lock file that is the issue. If you ignore the exception, all is well (not ideal).

**Comment by dnlcrl** [comment]
```
python2.7 pyscholar.py -c 1 --author "albert einstein" --phrase "quantum theory"

         Title Quantum theory of the monoatomic ideal gas
           URL http://www.condmat.uni-oldenburg.de/TeachingSP/einstein_2.ps
          Year 1924
     Citations 24
      Versions 2
    Cluster ID 16541064273269068150
Citations list http://scholar.google.com/scholar?cites=16541064273269068150&as_sdt=2005&sciodt=0,5&hl=en
 Versions list http://scholar.google.com/scholar?cluster=16541064273269068150&hl=en&as_sdt=0,5
       Excerpt In a treatment which has appeared recently in these proceedings (XXII 1924, p. 261) a theory of the “degeneracy” of ideal gases has been given, applying a method devised by Mr. D. Bose for the derivation of Planck's radiation formula. The interest in this theory stems  ...
       authors A Einstein - Proceedings of

```

I'm sorry but I can't reproduce the warning nor the error, it is working properly on my machine. 
You can try by updating firefox, selenium and BeautifulSoup.
